name: Check for broken links

on:
  push:
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --exclude-path README.md --exclude-path _pages/404.md --exclude-path _pages/blog.md --exclude-path _posts/2018-12-22-distill.md --verbose --no-progress './**/*.md' './**/*.html'
          # Adjust options for external links or retries
          skip-external: false  # Set to true to ignore external links
          retry-count: 3        # Number of retries for external links
          timeout: 20s          # Increase timeout for slow external links
